# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
  params:
    author-email: albertosadde@gmail.com
    author-name: Alberto Sadde
    copyright: 2018 Alberto Sadde
    github-username: aesadde
    category: Development
